2023-05-24 23:16:27,447 INFO: Microblog startup [in /Users/danielhsiao/microblog/app/__init__.py:43]
2023-05-24 23:46:54,399 INFO: Microblog startup [in /Users/danielhsiao/microblog/app/__init__.py:43]
2023-05-24 23:46:57,876 INFO: Microblog startup [in /Users/danielhsiao/microblog/app/__init__.py:43]
2023-05-25 00:08:02,165 INFO: Microblog startup [in /Users/danielhsiao/microblog/app/__init__.py:43]
2023-05-25 00:29:48,145 INFO: Microblog startup [in /Users/danielhsiao/microblog/app/__init__.py:43]
2023-05-25 01:06:13,447 INFO: Microblog startup [in /Users/danielhsiao/microblog/app/__init__.py:43]
2023-05-25 01:08:00,156 INFO: Microblog startup [in /Users/danielhsiao/microblog/app/__init__.py:43]
2023-05-25 01:19:26,034 INFO: Microblog startup [in /Users/danielhsiao/microblog/app/__init__.py:43]
2023-05-25 16:42:57,190 INFO: Microblog startup [in /Users/danielhsiao/microblog/app/__init__.py:43]
2023-05-25 16:44:11,016 ERROR: Exception on /user/danhsiao707 [GET] [in /Users/danielhsiao/microblog/venv/lib/python3.11/site-packages/flask/app.py:1414]
Traceback (most recent call last):
  File "/Users/danielhsiao/microblog/venv/lib/python3.11/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/danielhsiao/microblog/venv/lib/python3.11/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/danielhsiao/microblog/venv/lib/python3.11/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/danielhsiao/microblog/venv/lib/python3.11/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/danielhsiao/microblog/venv/lib/python3.11/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/danielhsiao/microblog/app/routes.py", line 82, in user
    return render_template('user.html', user=user, posts=posts)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/danielhsiao/microblog/venv/lib/python3.11/site-packages/flask/templating.py", line 151, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/danielhsiao/microblog/venv/lib/python3.11/site-packages/flask/templating.py", line 132, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/danielhsiao/microblog/venv/lib/python3.11/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/Users/danielhsiao/microblog/venv/lib/python3.11/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/danielhsiao/microblog/app/templates/user.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/danielhsiao/microblog/app/templates/base.html", line 32, in top-level template code
    {% block content %}{% endblock %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/danielhsiao/microblog/app/templates/user.html", line 17, in block 'content'
    {{ form.hidden_tag() }}
  File "/Users/danielhsiao/microblog/venv/lib/python3.11/site-packages/jinja2/environment.py", line 485, in getattr
    return getattr(obj, attribute)
           ^^^^^^^^^^^^^^^^^^^^^^^
jinja2.exceptions.UndefinedError: 'form' is undefined
2023-05-25 20:25:56,727 INFO: Microblog startup [in /Users/danielhsiao/microblog/app/__init__.py:45]
2023-05-25 20:35:43,080 INFO: Microblog startup [in /Users/danielhsiao/microblog/app/__init__.py:45]
2023-05-26 00:08:04,852 INFO: Microblog startup [in /Users/danielhsiao/microblog/app/__init__.py:45]
2023-05-26 00:23:45,078 INFO: Microblog startup [in /Users/danielhsiao/microblog/app/__init__.py:45]
2023-05-26 00:29:27,967 INFO: Microblog startup [in /Users/danielhsiao/microblog/app/__init__.py:45]
2023-05-26 00:29:41,603 INFO: Microblog startup [in /Users/danielhsiao/microblog/app/__init__.py:45]
2023-05-26 00:30:54,500 INFO: Microblog startup [in /Users/danielhsiao/microblog/app/__init__.py:45]
2023-05-26 00:33:20,645 INFO: Microblog startup [in /Users/danielhsiao/microblog/app/__init__.py:45]
2023-05-26 01:56:32,244 INFO: Microblog startup [in /Users/danielhsiao/microblog/app/__init__.py:45]
2023-05-26 01:57:51,111 ERROR: Exception on /user/danny [GET] [in /Users/danielhsiao/microblog/venv/lib/python3.11/site-packages/flask/app.py:1414]
Traceback (most recent call last):
  File "/Users/danielhsiao/microblog/venv/lib/python3.11/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/danielhsiao/microblog/venv/lib/python3.11/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/danielhsiao/microblog/venv/lib/python3.11/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/danielhsiao/microblog/venv/lib/python3.11/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/danielhsiao/microblog/venv/lib/python3.11/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/danielhsiao/microblog/app/routes.py", line 83, in user
    return render_template('user.html', user=user, posts=posts)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/danielhsiao/microblog/venv/lib/python3.11/site-packages/flask/templating.py", line 151, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/danielhsiao/microblog/venv/lib/python3.11/site-packages/flask/templating.py", line 132, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/danielhsiao/microblog/venv/lib/python3.11/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/Users/danielhsiao/microblog/venv/lib/python3.11/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/danielhsiao/microblog/app/templates/user.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/danielhsiao/microblog/app/templates/base.html", line 32, in top-level template code
    {% block content %}{% endblock %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/danielhsiao/microblog/app/templates/user.html", line 17, in block 'content'
    {{ form.hidden_tag() }}
  File "/Users/danielhsiao/microblog/venv/lib/python3.11/site-packages/jinja2/environment.py", line 485, in getattr
    return getattr(obj, attribute)
           ^^^^^^^^^^^^^^^^^^^^^^^
jinja2.exceptions.UndefinedError: 'form' is undefined
2023-05-26 02:15:23,823 INFO: Microblog startup [in /Users/danielhsiao/microblog/app/__init__.py:47]
2023-05-26 02:17:56,197 INFO: Microblog startup [in /Users/danielhsiao/microblog/app/__init__.py:47]
2023-05-29 16:35:43,499 INFO: Microblog startup [in /Users/danielhsiao/microblog/app/__init__.py:47]
2023-05-29 16:45:58,674 INFO: Microblog startup [in /Users/danielhsiao/microblog/app/__init__.py:47]
2023-05-30 14:37:03,840 INFO: Microblog startup [in /Users/danielhsiao/microblog/app/__init__.py:49]
